---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digibank-accounts
  labels:
    account: accounts

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accounts
  labels:
    chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
    app: accounts
    version: "{{ .Values.accounts.version }}"
spec:
  replicas: {{ .Values.accounts.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: accounts
        version: "{{ .Values.accounts.version }}"
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: digibank-accounts
      containers:
        - name: accounts
          image: "{{ .Values.accounts.image }}:{{ .Values.accounts.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: accounts-port
              containerPort: 3400
          livenessProbe:
            httpGet:
              path: "{{ .Values.livenessProbe.endpointPath}}"
              port: {{ .Values.accounts.servicePort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds}}
          readinessProbe:
            httpGet:
              path: "{{ .Values.readinessProbe.endpointPath}}"
              port: {{ .Values.accounts.servicePort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds}}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds}}
          resources:
            requests:
              cpu: "{{ .Values.image.resources.requests.cpu }}"
              memory: "{{ .Values.image.resources.requests.memory }}"
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: mongoUrl

---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
    app: accounts
    version: "{{ .Values.accounts.version }}"
spec:
  ports:
    - name: "{{ .Values.accounts.servicePortName }}"
      port: {{ .Values.accounts.servicePort }}
      targetPort: accounts-port
  selector:
    app: accounts

---
{{ if .Values.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: accounts-hpa-policy
  labels:
    app: accounts
    chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
    version: "{{ .Values.accounts.version }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: accounts
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage }}
{{ end }}

---