---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digibank-authentication
  labels:
    account: authentication

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authentication-deployment
  labels:
    chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
    app: authentication
    version: "{{ .Values.authentication.version }}"
spec:
  replicas: {{ .Values.authentication.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: authentication
        version: "{{ .Values.authentication.version }}"
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: digibank-authentication
      containers:
        - name: authentication
          image: "{{ .Values.authentication.image }}:{{ .Values.authentication.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: auth-port
              containerPort: 3200
          livenessProbe:
            httpGet:
              path: "{{ .Values.livenessProbe.endpointPath}}"
              port: {{ .Values.authentication.servicePort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds}}
          readinessProbe:
            httpGet:
              path: "{{ .Values.readinessProbe.endpointPath}}"
              port: {{ .Values.authentication.servicePort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds}}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds}}
          resources:
            requests:
              cpu: "{{ .Values.image.resources.requests.cpu }}"
              memory: "{{ .Values.image.resources.requests.memory }}"
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: mongoUrl

---
apiVersion: v1
kind: Service
metadata:
  name: authentication
  labels:
    chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
    app: authentication
    version: "{{ .Values.authentication.version }}"
spec:
  ports:
    - name: "{{ .Values.authentication.servicePortName }}"
      port: {{ .Values.authentication.servicePort }}
      targetPort: auth-port
  selector:
    app: authentication

---
{{ if .Values.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: authentication-hpa-policy
  labels:
    app: authentication
    chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
    version: "{{ .Values.authentication.version }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authentication-deployment
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage }}
{{ end }}

---