{{- if .Values.mongo.enabled -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.mongo.name }}-pvc"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    app: "{{ .Values.mongo.name }}"
    version: "{{ .Values.mongo.version }}"
spec:
  accessModes:
    - "{{ .Values.mongo.pvAccessMode }}"
  resources:
    requests:
      storage: "{{ .Values.mongo.pvSize }}"
{{- end -}}
