---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digibank-transactions
  labels:
    account: transactions

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: transactions-deployment
  labels:
    chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
    app: transactions
    version: "{{ .Values.transactions.version }}"
spec:
  replicas: {{ .Values.transactions.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: transactions
        version: "{{ .Values.transactions.version }}"
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: digibank-transactions
      containers:
        - name: transactions
          image: "{{ .Values.transactions.image }}:{{ .Values.transactions.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: trans-port
              containerPort: 3600
          livenessProbe:
            httpGet:
              path: "{{ .Values.livenessProbe.endpointPath}}"
              port: {{ .Values.transactions.servicePort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds}}
          readinessProbe:
            httpGet:
              path: "{{ .Values.readinessProbe.endpointPath}}"
              port: {{ .Values.transactions.servicePort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds}}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds}}
          resources:
            requests:
              cpu: "{{ .Values.image.resources.requests.cpu }}"
              memory: "{{ .Values.image.resources.requests.memory }}"
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: mongoUrl

---
apiVersion: v1
kind: Service
metadata:
  name: transactions
  labels:
    chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
    app: transactions
    version: "{{ .Values.transactions.version }}"
spec:
  ports:
    - name: "{{ .Values.transactions.servicePortName }}"
      port: {{ .Values.transactions.servicePort }}
      targetPort: trans-port
  selector:
    app: transactions

---
{{ if .Values.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
  name: transactions-hpa-policy
  app: transactions
  version: "{{ .Values.transactions.version }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transactions-deployment
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage }}
{{ end }}

---
