---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digibank-userbase
  labels:
    account: userbase

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: userbase-deployment
  labels:
    chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
    app: userbase
    version: "{{ .Values.userbase.version }}"
spec:
  replicas: {{ .Values.userbase.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: userbase
        version: "{{ .Values.userbase.version }}"
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: digibank-userbase
      containers:
        - name: userbase
          image: "{{ .Values.userbase.image }}:{{ .Values.userbase.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: userbase-port
              containerPort: 4200
          livenessProbe:
            httpGet:
              path: "{{ .Values.livenessProbe.endpointPath}}"
              port: {{ .Values.userbase.servicePort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds}}
          readinessProbe:
            httpGet:
              path: "{{ .Values.readinessProbe.endpointPath}}"
              port: {{ .Values.userbase.servicePort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds}}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds}}
          resources:
            requests:
              cpu: "{{ .Values.image.resources.requests.cpu }}"
              memory: "{{ .Values.image.resources.requests.memory }}"
          env:
            ##### Environment variables #####
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: mongoUrl
            - name: CURRENCY
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: currency
            ##### Accounts #####
            - name: DROP_ACCOUNTS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: dropAccountsEndpoint
            ##### Authentication #####
            - name: GET_USERS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: getUsersEndpoint
            ##### Bills #####
            - name: UPSERT_BILL_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: upsertBillEndpoint
            - name: DROP_BILLS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: dropBillsEndpoint
            ##### Transactions #####
            - name: CREATE_TRANSACTION_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: createTransactionEndpoint
            - name: DROP_TRANSACTIONS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: dropTransactionsEndpoint

---
apiVersion: v1
kind: Service
metadata:
  name: userbase
  labels:
    chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
    app: userbase
    version: "{{ .Values.userbase.version }}"
spec:
  ports:
    - name: "{{ .Values.userbase.servicePortName }}"
      port: {{ .Values.userbase.servicePort }}
      targetPort: userbase-port
  selector:
    app: userbase

---
{{ if .Values.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: userbase-hpa-policy
  labels:
    app: userbase
    chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
    version: "{{ .Values.userbase.version }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userbase-deployment
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage }}
{{ end }}

---
