---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc
  namespace: digibank
  labels:
    app: "mongo"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
