# apiVersion: policy.aspenmesh.io/v1alpha1
# kind: Application
# metadata:
#   name: digibank
# spec:
#   inbound:
#     ports:
#     - number: 3000
#       protocol: HTTP
#       paths:
#       - expose:
#           public: true
#           jwtSecured: false
#         uri:
#           prefix: /
#       # - expose:
#       #     public: true
#       #     jwtSecured: false
#       #   uri:
#       #     exact: /vendors/css/normalize.css
#       # - expose:
#       #     public: true
#       #     jwtSecured: true
#       #   uri:
#       #     exact: /endpoints/accounts/activate
#       # - expose:
#       #     public: true
#       #     jwtSecured: true
#       #   uri:
#       #     exact: /endpoints/accounts/get
#       # - expose:
#       #     public: true
#       #     jwtSecured: true
#       #   uri:
#       #     exact: /endpoints/accounts/transfer
#       # - expose:
#       #     public: true
#       #     jwtSecured: true
#       #   uri:
#       #     exact: /endpoints/auth
#       # - expose:
#       #     public: true
#       #     jwtSecured: true
#       #   uri:
#       #     exact: /endpoints/bills/get
#       # - expose:
#       #     public: true
#       #     jwtSecured: true
#       #   uri:
#       #     exact: /endpoints/bills/pay
#       # - expose:
#       #     public: true
#       #     jwtSecured: true
#       #   uri:
#       #     exact: /endpoints/login
#       # - expose:
#       #     public: true
#       #     jwtSecured: true
#       #   uri:
#       #     exact: /endpoints/logout
#       # - expose:
#       #     public: true
#       #     jwtSecured: false
#       #   uri:
#       #     exact: /endpoints/signup
#       # - expose:
#       #     public: true
#       #     jwtSecured: false
#       #   uri:
#       #     exact: /endpoints/support/chat
#       # - expose:
#       #     public: true
#       #     jwtSecured: true
#       #   uri:
#       #     exact: /endpoints/transactions/get
# ---
# apiVersion: policy.aspenmesh.io/v1alpha1
# kind: SecureIngress
# metadata:
#   name: digibank
#   annotations:
#     external-dns.alpha.kubernetes.io/target: 10.1.1.5
# spec:
#   domainName: "digibank.aspen-demo.org"
#   jwt:
#   - issuer: "admin@digibank.aspen-demo.org"
#     jwksUri: "https://10.1.1.4:4444/.well-known/jwks.json"
#   exposedApplications:
#   - applicationReference:
#       name: digibank
#       namespace: digibank
#     serviceReference:
#       name: portal
#       namespace: digibank
