apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: digibank
  namespace: digibank
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: "digibank"
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
    hosts:
    - "digibank.aspen-demo.org:31390"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: digibank
  namespace: digibank
spec:
  hosts:
  - "digibank.aspen-demo.org:31390"
  gateways:
  - digibank
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 3000
        host: portal
