apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: digibank
  annotations:
    policy.aspenmesh.io/externaldns: "true"
    external-dns.alpha.kubernetes.io/target: 10.1.1.5
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: "digibank"
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
    hosts:
    - "digibank.aspen-demo.org"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: digibank
spec:
  hosts:
  - "digibank.aspen-demo.org"
  gateways:
  - digibank
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 3000
        host: portal
